#!/bin/sh
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA

#
# Detects the system's country code based on the timezone.
#
# @return {string} The two-letter country code in lowercase (e.g., "us", "br").
#
detect_cc() {
    tz=$(timedatectl show --value -p Timezone 2>/dev/null || cat /etc/timezone 2>/dev/null)
    [ -z "$tz" ] && return
    grep -E "\s${tz}$" /usr/share/zoneinfo/zone.tab 2>/dev/null | awk 'NR==1{print tolower($1)}'
}

#
# Generates a list of NTP servers based on the country code.
#
# @param {string} $1 - The two-letter country code. If "br", uses Brazilian
#   servers. Otherwise, uses the generic NTP pool for that country.
# @return {string} A multi-line string of server configurations.
#
generate_servers() {
    cc="$1"
    if [ "$cc" = "br" ]; then
        cat <<EOF
server a.st1.ntp.br    iburst prefer
server b.st1.ntp.br    iburst
server c.st1.ntp.br    iburst
EOF
    else
        prefix="${cc:+$cc.}"
        cat <<EOF
server 0.${prefix}pool.ntp.org    iburst
server 1.${prefix}pool.ntp.org    iburst
server 2.${prefix}pool.ntp.org    iburst
server 3.${prefix}pool.ntp.org    iburst
EOF
    fi
}

#
# Installs the NTP configuration file.
#
# This function creates `/etc/sparky-ntp.conf` from the `etc/sparky-ntp.conf`
# template, replacing the `@NTP_SERVERS@` placeholder with the appropriate
# server list generated by `generate_servers`.
#
install_conf() {
    cc=$(detect_cc)
    servers=$(generate_servers "$cc")
    dest=/etc/sparky-ntp.conf
    {
        while IFS= read -r line; do
            case "$line" in
                *'@NTP_SERVERS@'*) printf '%s\n' "$servers" ;;
                *) printf '%s\n' "$line" ;;
            esac
        done < etc/sparky-ntp.conf
    } > "$dest"
}

#
# Loads the appropriate translation file based on the system's language.
#
# This function detects the system's language from the LANG environment
# variable and sources the corresponding translation file from the `locale`
# directory. If a specific translation is not found, it defaults to English.
#
load_translations() {
    lang=$(echo "$LANG" | cut -d'_' -f1)
    # Default to English if no language is set
    if [ -z "$lang" ]; then
        lang="en"
    fi
    # Source the translation file, defaulting to English if not found
    if [ -f "locale/${lang}.sh" ]; then
        . "locale/${lang}.sh"
    else
        . "locale/en.sh"
    fi
}

main() {
    load_translations

    if [ "$(id -u)" -ne 0 ]; then
        echo "$MSG_MUST_BE_ROOT" >&2
        exit 1
    fi

    if [ "$1" = "uninstall" ]; then
        echo "$MSG_UNINSTALLING"
        rm -f /etc/sparky-ntp.conf
        echo "$MSG_UNINSTALLATION_COMPLETE"
    else
        echo "$MSG_INSTALLING"
        install_conf
        echo "$MSG_INSTALLATION_COMPLETE"
    fi
}

if [ "$0" = "install.sh" ] || [ "$0" = "./install.sh" ]; then
    main "$@"
fi
